### ISSUE TITLE
DataCollatorSelfAsk

### ISSUE THREAD

**Issue by CuteMing** [oriyor/ret-robust#4]
from data_collator import DataCollatorSelfAsk

ModuleNotFoundError: No module named 'data_collator
ImportError: cannot import name 'DataCollatorSelfAsk' from 'transformers.data.data_collator'

This module is not found, can you upload the requirements.txt, or the version of transformers, thanks!!

**Comment by oriyor** [comment]
Hi, sorry for the late response, please see fix here - https://github.com/oriyor/ret-robust/issues/6
