### ISSUE TITLE
DataCollat​​orSelfAsk

### ISSUE THREAD

**Issue by fionandz** [oriyor/ret-robust#6]
Hi,
Thanks for your awesome paper and code.Would you be able to share the implementation details of the DataCollatorSelfAsk class? Thank you very much for your assistance.

**Comment by Yueeeeeeee** [comment]
Same question here:)

**Comment by oriyor** [comment]
hi! 

Sorry for the late response. Please see https://github.com/oriyor/ret-robust/blob/main/training/scripts/data_collator.py.

The logic is pretty simple - mask everything before the intermediate questions and answers.

Hope it helps and please let me know if you have any additional issues!
